version: '3'

services:
  se-server:
    image: mmmaxwwwell/space-engineers-dedicated-docker-linux:latest
    container_name: SpaceEngineers
    restart: unless-stopped
    volumes:
      - ./appdata/space-engineers/config/World:/appdata/space-engineers/World
      - ./appdata/space-engineers/config/Plugins:/appdata/space-engineers/Plugins
      - ./appdata/space-engineers/config/SpaceEngineers-Dedicated.cfg:/appdata/space-engineers/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg
      - ./appdata/space-engineers/bins/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated
      - ./appdata/space-engineers/bins/steamcmd:/home/wine/.steam
    ports:
     - "27016:27016/udp"
     
networks:                                
  se-net: 
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1400